# Generated by Django 3.0.5 on 2024-04-16 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='after_donate_blood',
            field=models.DateField(default=datetime.datetime(2024, 4, 16, 11, 45, 20, 399093)),
        ),
    ]
